version: '2'
services: 
    web: 
      build: .
      command: npm run start
      volumes: 
        - .:/user/app/
        - /user/app/node_modules
      ports: 
        - '3000:3000'
      links: 
        - mongo
    mongo:
      image: mongo
      ports: 
        - "27018:27017"
      

